config/routes.rb
Blog2::Application.routes.draw do
  

  devise_for :admins, :controllers => {:welcome => "adminwelcome", :categories => "admin/categories", 
    :posts => "admin/posts", :ccomments => "admin/comments"}

  namespace :admin do 
    resources :categories

    resources :posts do
      resources :comments
    end
    get "welcome/index"
  end

  get "welcome/index"

  resources :categories

  resources :posts do
    resources :comments
  end

  root to: "welcome#index"

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts

	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :category
	has_many :comments, dependent: :destroy

	validates :title, presence: true
    validates :text, presence: true,
                    length: { minimum: 5 }
end

app/controllers/admin/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminsController
  
	def new
		@category = Category.new
	end

	def create
  		@category = Category.new(params[:category].permit(:name))
 
  		if @category.save
    		redirect_to admin_category_path(@category)
  		else
    		render 'new'
  		end
	end

  def show
      @category = Category.new
      @category = Category.find(params[:id])
  end

  def index
    @categories = Category.all
  end

  def edit
      @category = Category.find(params[:id])
  end

  def update
      @category = Category.find(params[:id])
 
      if @category.update(params[:category].permit(:name))
        redirect_to admin_category_path(@category)
      else
        render 'edit'
      end
  end

  def destroy
      @category = Category.find(params[:id])
      @category.destroy
 
      redirect_to admin_categories_path
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminsController
	def create
    	@post = Post.find(params[:post_id])
   		@comment = @post.comments.create(params[:comment].permit(:author, :body))
    	redirect_to admin_post_path(@post)
  	end

  	def destroy
    	@post = Post.find(params[:post_id])
    	@comment = @post.comments.find(params[:id])
    	@comment.destroy
    	redirect_to admin_post_path(@post)
  	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminsController
	def new
		@post = Post.new
	end

	def create
  		@post = Post.new(params[:post].permit(:title, :text))
 
  		#if @post.save
    	#	redirect_to admin_post_path(@post)
  		#else
    	#	render 'new'
  		#end
    begin
      Admin::PostCreationService.new.process(@post)
    rescue Admin::PostCreationService::PostCreationError
      render 'new'
    end

      redirect_to admin_post_path(@post)
	end

	def show
  		@post = Post.find(params[:id])
	end

	def index
 		@posts = Post.all
	end

	def edit
  		@post = Post.find(params[:id])
	end

	def update
  		@post = Post.find(params[:id])
 
  		if @post.update(params[:post].permit(:title, :text))
    		redirect_to admin_post_path(@post)
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@post = Post.find(params[:id])
  		@post.destroy
 
  		redirect_to admin_posts_path
	end
 
	private
  	def post_params
    	params.require(:post).permit(:title, :text)
  	end

end

class Admin::PostCreationService

  class PostCreationError < StandardError; end

  def intialize
  end

  def process(post)
    unless post.save 
      raise PostCreationError.new
    end
  end

end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < AdminsController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
  def show
      @category = Category.new
      @category = Category.find(params[:id])
  end


  def index
    @categories = Category.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    	@post = Post.find(params[:post_id])
   		@comment = @post.comments.create(params[:comment].permit(:author, :body))
    	redirect_to post_path(@post)
  	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def show
  		@post = Post.find(params[:id])
	end

	def index
 		@posts = Post.all
	end
 
	private
  	def post_params
    	params.require(:post).permit(:title, :text)
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/categories/edit.html.erb
<h1> Editing category </h1>

<%= form_for @category, url: admin_category_path(@category.id), method: :patch do |f| %>
<% if @category.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@category.errors.count, "error") %> occurred:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Listing categories</h1>
 
<%= link_to 'New category', new_admin_category_path %>

<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Show', admin_category_path(category) %></td>
      <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
      <td><%= link_to 'Destroy', admin_category_path(category),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Main Page", controller: "welcome" %>

app/views/admin/categories/new.html.erb
<h1> New category </h1>

<%= form_for @category, url: admin_categories_path do |f| %>
<% if @category.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@category.errors.count, "error") %> occurred:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
 
 <%= link_to 'Edit', edit_admin_category_path(@category) %> | <%= link_to 'Back', admin_categories_path %>

app/views/admin/comments/_comment.html.erb
<p>
  <strong>Author:</strong>
  <%= comment.author %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/admin/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/posts/_form.html.erb
<%= form_for @post, url: admin_posts_path do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= form_for @post, url: admin_post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %> 
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<h1>Listing posts</h1>
 
<%= link_to 'New post', new_admin_post_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', admin_post_path(post) %></td>
      <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
      <td><%= link_to 'Destroy', admin_post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Main Page", controller: "welcome" %>

app/views/admin/posts/new.html.erb
<h1> New post </h1>

<%= form_for @post, url: admin_posts_path do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_admin_post_path(@post) %> | <%= link_to 'Back', admin_posts_path %>

app/views/admin/welcome/index.html.erb
<h1>Welcome to the blog</h1>

<%= link_to "Posts", controller: "posts" %> ||

<%= link_to "Categories", controller: "categories" %> ||

<%= link_to "Sing in", controller: "devise/sessions", action: "new" %> ||

<%= link_to "Sing up", controller: "devise/registrations", action: "new" %>   ||

<%= link_to "Sing out", controller: "devise/registrations", action: "destroy" %> 

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Main Page", controller: "welcome" %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
 
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Author:</strong>
  <%= comment.author %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
 

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Main Page", controller: "welcome" %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome to the blog</h1>

<%= link_to "Posts", controller: "posts" %> ||

<%= link_to "Categories", controller: "categories" %>